config/routes.rb
Filedart::Application.routes.draw do
  resources :darts

  
  match '/upload_start' => 'darts#upload_start'
  match '/upload_update' => 'darts#upload_update'
  match '/upload_complete' => 'darts#upload_complete'

end

app/models/dart.rb
class Dart < ActiveRecord::Base
  attr_accessible :name, :percentage, :size, :url, :token, :completed
  
  before_create :generate_token
  
  protected

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64
      break random_token unless Dart.where(token: random_token).exists?
    end
  end
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/darts_controller.rb
class DartsController < ApplicationController
  # GET /darts
  # GET /darts.json
  def index
    @darts = Dart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @darts }
    end
  end

  # GET /darts/1
  # GET /darts/1.json
  def show
    @dart = Dart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dart }
    end
  end
  
  
  
  def upload_start
   @name = params[:name]
   @size = params[:size]
   
   @dart = Dart.new(:name=>@name, :size=>@size, :percentage=>0.0, :url => "www.test.com", :completed => false)
   
   respond_to do |format|
     if @dart.save
       format.html 
       format.json { render json: @dart, status: :created, location: @dart }
     else
       format.html 
       format.json { render json: @dart.errors, status: :unprocessable_entity }
     end
   end
  end


  
  def upload_update
    @token = params[:token]
    @uploaded = params[:uploaded]
    
    @dart = Dart.find_by_token(@token)
    
    if @dart
      @dart.percentage = @uploaded
      respond_to do |format|
         if @dart.save
           format.html 
           format.json { render json: @dart, status: :updated, location: @dart }
         else
           format.html 
           format.json { render json: @dart.errors, status: :unprocessable_entity }
         end
       end
    else
      #DART DOES NOT EXIST
    end
  end
  
  def upload_complete
    @token = params[:token]
    
    @dart = Dart.find_by_token(@token)
  
    if @dart
      @dart.percentage = 100.0
      @dart.completed = true
      respond_to do |format|
         if @dart.save
           format.html 
           format.json { render json: @dart, status: :completed, location: @dart }
         else
           format.html 
           format.json { render json: @dart.errors, status: :unprocessable_entity }
         end
       end
    else
      #DART DOES NOT EXIST
    end
  end
  
  
  
  
  
  

  # GET /darts/new
  # GET /darts/new.json
  def new
    @dart = Dart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dart }
    end
  end

  # GET /darts/1/edit
  def edit
    @dart = Dart.find(params[:id])
  end

  # POST /darts
  # POST /darts.json
  def create
    @dart = Dart.new(params[:dart])

    respond_to do |format|
      if @dart.save
        format.html { redirect_to @dart, notice: 'Dart was successfully created.' }
        format.json { render json: @dart, status: :created, location: @dart }
      else
        format.html { render action: "new" }
        format.json { render json: @dart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /darts/1
  # PUT /darts/1.json
  def update
    @dart = Dart.find(params[:id])

    respond_to do |format|
      if @dart.update_attributes(params[:dart])
        format.html { redirect_to @dart, notice: 'Dart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /darts/1
  # DELETE /darts/1.json
  def destroy
    @dart = Dart.find(params[:id])
    @dart.destroy

    respond_to do |format|
      format.html { redirect_to darts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/darts_helper.rb
module DartsHelper
end

app/views/darts/_form.html.erb
<%= form_for(@dart) do |f| %>
  <% if @dart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dart.errors.count, "error") %> prohibited this dart from being saved:</h2>

      <ul>
      <% @dart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :percentage %><br />
    <%= f.text_field :percentage %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/darts/edit.html.erb
<h1>Editing dart</h1>

<%= render 'form' %>

<%= link_to 'Show', @dart %> |
<%= link_to 'Back', darts_path %>

app/views/darts/index.html.erb
<h1>Listing darts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Percentage</th>
	<th>Url</th>
	<th>Token</th>
	<th>Completed</th>
    <th></th>
    <th></th>
	<th></th>
  </tr>

<% @darts.each do |dart| %>
  <tr>
    <td><%= dart.name %></td>
    <td><%= dart.size %></td>
    <td><%= dart.percentage %></td>
	<td><%= dart.url %></td>
	<td><%= dart.token %></td>
	<td><%= dart.completed %></td>
    <td><%= link_to 'Show', dart %></td>
    <td><%= link_to 'Edit', edit_dart_path(dart) %></td>
    <td><%= link_to 'Destroy', dart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dart', new_dart_path %>

app/views/darts/new.html.erb
<h1>New dart</h1>

<%= render 'form' %>

<%= link_to 'Back', darts_path %>

app/views/darts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dart.name %>
</p>

<p>
  <b>Size:</b>
  <%= @dart.size %>
</p>

<p>
  <b>Percentage:</b>
  <%= @dart.percentage %>
</p>

<p>
  <b>Url:</b>
  <%= @dart.url %>
</p>

<p>
  <b>Token:</b>
  <%= @dart.token %>
</p>

<p>
  <b>Completed:</b>
  <%= @dart.completed %>
</p>


<%= link_to 'Edit', edit_dart_path(@dart) %> |
<%= link_to 'Back', darts_path %>

app/views/darts/upload_complete.erb
<%=@dart.to_json%>

app/views/darts/upload_start.html.erb
<%=@dart.to_json%>

app/views/darts/upload_update.html.erb
<%=@dart.to_json%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filedart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>